#!/bin/tcsh

set ssid = `iwlist wlan0 scan | grep ESSID | awk '{print $1}' | cut -d \" -f2

if ( $ssid == "TNCAPBA6E09_EXT" ) then
  echo "163B76E17C"
else if ( $ssid == "Vodafone-33559311_EXT" ) then
  echo "vltxa9le6fypvj8"
else if ( $ssid == "omero" ) then
  echo "sigl8{ossida"
else
  echo "Not connected"
endif
